force-app/main/default/objects/Medical_Appointment__c/Medical_Appointment__c.object-meta.xml
<CustomObject>
    <label>Medical Appointment</label>
    <nameField>
        <label>Medical Appointment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Medical Appointments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Medical_Appointment__c/fields/Doctor__c.field-meta.xml
<CustomField>
    <fullName>Doctor__c</fullName>
    <label>Doctor</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Person__c.RecordType.Id</field>
            <operation>equals</operation>
            <value>012KL000000XeBUYA0</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Person__c</referenceTo>
    <relationshipLabel>Medical Appointments (Doctor)</relationshipLabel>
    <relationshipName>Doctor_Medical_Appointments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Medical_Appointment__c/fields/Patient__c.field-meta.xml
<CustomField>
    <fullName>Patient__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Patient</label>
    <referenceTo>Person__c</referenceTo>
    <relationshipLabel>Medical Appointments</relationshipLabel>
    <relationshipName>Medical_Appointments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Person__c/Person__c.object-meta.xml
<CustomObject>
    <label>Person</label>
    <nameField>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Persons</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/FirstAppointmentInternistClass.cls
public class FirstAppointmentInternistClass 
{
    public static void firstAppointmentInternist(List<Medical_Appointment__c> appointments) 
    {
        Set<Id> patientIds = new Set<Id>();
        for (Medical_Appointment__c app : appointments) {
            patientIds.add(app.Patient__c);
        }
        
            
        Map<Id, Medical_Appointment__c> all_app_int = new Map<Id, Medical_Appointment__c>([SELECT Id, Patient__c
                                           FROM Medical_Appointment__c 
                                           WHERE Patient__c IN :patientIds AND Doctor__r.Specialization__c = 'Internist']);
    Map<Id, Person__c> listint = new Map<Id, Person__c>([SELECT Id,Specialization__c FROM Person__c WHERE Specialization__c = 'Internist']);

    final Id OnlineR = Schema.SObjectType.Medical_Appointment__c.getRecordTypeInfosByDeveloperName().get('Online').getRecordTypeId();

        for (Medical_Appointment__c app : appointments) {
             if (!all_app_int.containsKey(app.Patient__c) && listint.containsKey(app.Doctor__c) && listint.get(app.Doctor__c).Specialization__c!=null) {
                if (listint.get(app.Doctor__c).Specialization__c == 'Internist' && app.RecordTypeId == OnlineR) {
                    app.addError('The first appointment to the internist must be on site');
                }
            }
    	}
    }
}