force-app/main/default/objects/Medical_Appointment__c/Medical_Appointment__c.object-meta.xml
<CustomObject>
    <label>Medical Appointment</label>
    <nameField>
        <label>Medical Appointment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Medical Appointments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Medical_Appointment__c/fields/Appointment_Time__c.field-meta.xml
<CustomField>
    <fullName>Appointment_Time__c</fullName>
    <label>Appointment Time</label>
    <required>true</required>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Medical_Appointment__c/fields/Doctor__c.field-meta.xml
<CustomField>
    <fullName>Doctor__c</fullName>
    <label>Doctor</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Person__c.RecordType.Id</field>
            <operation>equals</operation>
            <value>012KL000000XeBUYA0</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Person__c</referenceTo>
    <relationshipLabel>Medical Appointments (Doctor)</relationshipLabel>
    <relationshipName>Doctor_Medical_Appointments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Medical_Appointment__c/fields/Medical_Appointment_Name__c.field-meta.xml
<CustomField>
    <fullName>Medical_Appointment_Name__c</fullName>
    <label>Medical Appointment Name</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Medical_Appointment__c/fields/Medical_Facility__c.field-meta.xml
<CustomField>
    <fullName>Medical_Facility__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Medical Facility</label>
    <referenceTo>Medical_Facility__c</referenceTo>
    <relationshipLabel>Medical Appointments</relationshipLabel>
    <relationshipName>Medical_Appointments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Medical_Appointment__c/fields/Patient__c.field-meta.xml
<CustomField>
    <fullName>Patient__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Patient</label>
    <referenceTo>Person__c</referenceTo>
    <relationshipLabel>Medical Appointments</relationshipLabel>
    <relationshipName>Medical_Appointments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Medical_Facility__c/fields/Insurence_Required__c.field-meta.xml
<CustomField>
    <fullName>Insurence_Required__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Insurence Required</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Medical_Facility__c/fields/Medical_Facility_Name__c.field-meta.xml
<CustomField>
    <fullName>Medical_Facility_Name__c</fullName>
    <label>Medical Facility Name</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Person__c/Person__c.object-meta.xml
<CustomObject>
    <label>Person</label>
    <nameField>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Persons</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Person__c/fields/Personal_ID_Number__c.field-meta.xml
<CustomField>
    <fullName>Personal_ID_Number__c</fullName>
    <description>PESEL</description>
    <label>Personal ID Number</label>
    <length>11</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/AppointmentNameTriggerTest.cls
@isTest
public class AppointmentNameTriggerTest {
    @isTest
    static void testTriggerWithAllFieldsPopulated() {
        
        final Id DOCTOR_RECORD_TYPE_ID = Schema.SObjectType.Person__c.getRecordTypeInfosByDeveloperName().get('Doctor').getRecordTypeId();
    
		final Id PATIENT_RECORD_TYPE_ID = Schema.SObjectType.Person__c.getRecordTypeInfosByDeveloperName().get('Patient').getRecordTypeId();
        
        Medical_Facility__c facility = new Medical_Facility__c(Medical_Facility_Name__c = 'City Hospital na ulicy jana pawla 3 123424632hnirenfbivfdinvi nwefij ije rivneixn',Insurence_Required__c=false);
        insert facility;

        Person__c doctor = new Person__c(FirstName__c='Adam',LastName__c = 'Smith',Personal_ID_Number__c = '44051401458', RecordTypeId = DOCTOR_RECORD_TYPE_ID);
        insert doctor;

        Person__c patient = new Person__c(FirstName__c='Adaam',LastName__c = 'Johnson',Personal_ID_Number__c = '44051401458', RecordTypeId = PATIENT_RECORD_TYPE_ID);
        insert patient;

        Medical_Appointment__c appointment = new Medical_Appointment__c(
            Medical_Facility__c = facility.Id,
            Doctor__c = doctor.Id,
            Patient__c = patient.Id,
            Appointment_Time__c = System.now()
        );

        insert appointment;

        appointment = [SELECT Medical_Appointment_Name__c FROM Medical_Appointment__c WHERE Id = :appointment.Id];
        system.Debug(appointment.Medical_Appointment_Name__c);
        String name1='[City Hospital na ulicy jana pawla 3 123424632hnirenfbivfdinvi nwefij ije rivneixn]-[Smith]-[Johnson]-[' + (System.now()).format('dd-MM-yyyy') + ']';
        System.assertEquals(name1,
            appointment.Medical_Appointment_Name__c
        );
    }
    @isTest
    static void testTriggerWithMissingFields() {
        
        final Id DOCTOR_RECORD_TYPE_ID = Schema.SObjectType.Person__c.getRecordTypeInfosByDeveloperName().get('Doctor').getRecordTypeId();
    
		final Id PATIENT_RECORD_TYPE_ID = Schema.SObjectType.Person__c.getRecordTypeInfosByDeveloperName().get('Patient').getRecordTypeId();
        
        Person__c patient = new Person__c(LastName__c = 'Smiwh',FirstName__c='Aaaadam',Personal_ID_Number__c = '44051401458', RecordTypeId = PATIENT_RECORD_TYPE_ID);
        insert patient;
        Person__c doctor = new Person__c(LastName__c = 'Smitasfh',FirstName__c='Asasadam',Personal_ID_Number__c = '44051401458', RecordTypeId = DOCTOR_RECORD_TYPE_ID);
        insert doctor;

        Medical_Appointment__c appointment = new Medical_Appointment__c(
            Doctor__c = doctor.Id,
            Patient__c=patient.Id,
            Appointment_Time__c = System.now()
        );

        insert appointment;

        appointment = [SELECT Medical_Appointment_Name__c FROM Medical_Appointment__c WHERE Id = :appointment.Id];
        system.Debug(appointment.Medical_Appointment_Name__c);
        System.assertEquals(
            '[??]-[Smitasfh]-[Smiwh]-[' + (System.now()).format('dd-MM-yyyy') + ']',
            appointment.Medical_Appointment_Name__c
        );
    }
}