force-app/main/default/objects/Person__c/Person__c.object-meta.xml
<CustomObject>
    <label>Person</label>
    <nameField>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Persons</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Person__c/fields/Personal_ID_Number__c.field-meta.xml
<CustomField>
    <fullName>Personal_ID_Number__c</fullName>
    <description>PESEL</description>
    <label>Personal ID Number</label>
    <length>11</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/testValidatePersonalID.cls
@isTest
private class testValidatePersonalID
{
    @isTest
    static void testValidPESEL()
    {
        
        Person__c person = new Person__c
        (
        	Personal_ID_Number__c = '44051401359'        
        );
        
        try
        {
            insert person;
            Assert.areEqual(person.Personal_ID_Number__c, '44051401359', 'Something wrong happened!');
        }
        catch(DmlException e)
        {
            System.assert(false, 'Record should be inserted succesfully!');
        }
        
    }
    
    @isTest
    static void testInvalidLength()
    {
        Person__c person = new Person__c
        (
        	Personal_ID_Number__c = '4405140135'        
        );
        
        try 
        {
            insert person;
            System.assert(false, 'Record should not be inserted due to invalid Personal ID Number length!');
        } 
        catch (DmlException e) 
        {
            System.assert(e.getMessage().contains('Personal ID Number should be 11 digits long!'), 
                          'Expected validation error for invalid Personal ID Number length!');
        }
        
    }
    
    @isTest
    static void testInvalidLastDigit() 
    {
       
        Person__c person = new Person__c
        (
        	Personal_ID_Number__c = '44051401350'        
        );

        try 
        {
            insert person;
            System.assert(false, 'Record should not be inserted due to invalid last digit of Personal ID Number!');
        } 
        catch (DmlException e) 
        {
            System.assert(e.getMessage().contains('Last digit of Personal ID Number is wrong!'), 
                          'Expected validation error for invalid last digit of Personal ID Number!');
        }
    }
}